CREATE INDEX "TRANSACTIONAL"."RFA_CLAIM_ID_IDX" ON "TRANSACTIONAL"."RFA" ("CLAIM_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_SF_REQUEST_ID_IDX" ON "TRANSACTIONAL"."RFA" ("SF_REQUEST_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_DIAGNOSIS_RFA_ID_IDX" ON "TRANSACTIONAL"."RFA_DIAGNOSIS" ("RFA_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_DIAGNOSIS_DIAGNOSIS_ID_IDX" ON "TRANSACTIONAL"."RFA_DIAGNOSIS" ("DIAGNOSIS_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_DIAG_PROC_RFA_PROC_ID_IDX" ON "TRANSACTIONAL"."RFA_DIAGNOSIS_PROCEDURES" ("RFA_PROCEDURE_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_DIAG_PROC_RFA_DIAG_ID_IDX" ON "TRANSACTIONAL"."RFA_DIAGNOSIS_PROCEDURES" ("RFA_DIAGNOSIS_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_DIAG_PROC_STATUS_ID_IDX" ON "TRANSACTIONAL"."RFA_DIAGNOSIS_PROCEDURES" ("STATUS_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_PRC_STA_HIS_RFA_PRC_ID_IDX" ON "TRANSACTIONAL"."RFA_PROCECURE_STATUS_HISTORY" ("RFA_PROCEDURE_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_PRC_STA_HIS_NEW_STA_ID_IDX" ON "TRANSACTIONAL"."RFA_PROCECURE_STATUS_HISTORY" ("NEW_STATUS_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_PRC_STA_HIS_PRV_STA_ID_IDX" ON "TRANSACTIONAL"."RFA_PROCECURE_STATUS_HISTORY" ("PREVIOUS_STATUS_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_PRC_RFA_ID_IDX" ON "TRANSACTIONAL"."RFA_PROCEDURE" ("RFA_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_PRC_PRC_ID_IDX" ON "TRANSACTIONAL"."RFA_PROCEDURE" ("PROCEDURE_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_PRC_STA_ID_IDX" ON "TRANSACTIONAL"."RFA_PROCEDURE" ("STATUS_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_PRC_SRC_OF_DECISION_ID_IDX" ON "TRANSACTIONAL"."RFA_PROCEDURE" ("SOURCE_OF_DECISION_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";


  CREATE INDEX "TRANSACTIONAL"."RFA_PRC_SF_PRC_ID_IDX" ON "TRANSACTIONAL"."RFA_PROCEDURE" ("SF_PROCEDURE_ID")
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01";
