--------------------------------------------------------
--  DDL for Table DIAGNOSIS
--------------------------------------------------------

  CREATE TABLE "PARAMETERS"."DIAGNOSIS" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 145 CACHE 20 NOORDER  NOCYCLE , 
	"CODE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	"DATE_INSERT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"DATE_UPDATE" TIMESTAMP (6) DEFAULT NULL, 
	"DATE_DELETE" TIMESTAMP (6) DEFAULT NULL, 
	"DELETED" VARCHAR2(1 BYTE) DEFAULT 'F', 
	"VERSION" NUMBER(6,0) DEFAULT 1, 
	"USER_REQUEST_ID" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
--------------------------------------------------------
--  DDL for Index PAR_DIAG_CODE_IDX
--------------------------------------------------------

  CREATE INDEX "PARAMETERS"."PAR_DIAG_CODE_IDX" ON "PARAMETERS"."DIAGNOSIS" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01" ;
--------------------------------------------------------
--  DDL for Index PAR_DIAG_CODE_FX_IDX
--------------------------------------------------------

  CREATE INDEX "PARAMETERS"."PAR_DIAG_CODE_FX_IDX" ON "PARAMETERS"."DIAGNOSIS" (UPPER("CODE")) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01" ;
--------------------------------------------------------
--  DDL for Index DIAGNOSIS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PARAMETERS"."DIAGNOSIS_PK" ON "PARAMETERS"."DIAGNOSIS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01" ;
--------------------------------------------------------
--  Constraints for Table DIAGNOSIS
--------------------------------------------------------

  ALTER TABLE "PARAMETERS"."DIAGNOSIS" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "PARAMETERS"."DIAGNOSIS" MODIFY ("DELETED" NOT NULL ENABLE);
  ALTER TABLE "PARAMETERS"."DIAGNOSIS" MODIFY ("DATE_INSERT" NOT NULL ENABLE);
  ALTER TABLE "PARAMETERS"."DIAGNOSIS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "PARAMETERS"."DIAGNOSIS" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "PARAMETERS"."DIAGNOSIS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PARAMETERS"."DIAGNOSIS" ADD CONSTRAINT "DIAGNOSIS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01"  ENABLE;
