-- CONNECT SYS
ALTER SESSION SET EVENTS '10150 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10904 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '25475 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10407 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '10851 TRACE NAME CONTEXT FOREVER, LEVEL 1';
ALTER SESSION SET EVENTS '22830 TRACE NAME CONTEXT FOREVER, LEVEL 192 ';
-- new object type path: SCHEMA_EXPORT/USER
-- CONNECT SYSTEM
 CREATE USER "SECURITY" IDENTIFIED BY VALUES 'S:4E32DB02BF3C1E90AC190B8B267B92E9FFE8B287C453D87AE8B71A458D91;H:36571D5FAE75E89677B2FD2E28B30B0A;T:E0F17FD370EE2B999F9737C23CD1C0592901BD75089F9DE8CBEF446FF7AA267A68BB385936287874FA89FB64879153E411BBD9D003C06231C9D4651A4F98D7324135359461D450DA492EB9D0B09FAFF6;C709383CC2325765'
      DEFAULT TABLESPACE "DATA01"
      TEMPORARY TABLESPACE "TEMP";
-- new object type path: SCHEMA_EXPORT/SYSTEM_GRANT
GRANT READ ANY TABLE TO "SECURITY";
GRANT ALTER ANY CUBE BUILD PROCESS TO "SECURITY";
GRANT SELECT ANY CUBE BUILD PROCESS TO "SECURITY";
GRANT ALTER ANY MEASURE FOLDER TO "SECURITY";
GRANT SELECT ANY MEASURE FOLDER TO "SECURITY";
GRANT EXEMPT DDL REDACTION POLICY TO "SECURITY";
GRANT EXEMPT DML REDACTION POLICY TO "SECURITY";
GRANT LOGMINING TO "SECURITY";
GRANT CREATE ANY CREDENTIAL TO "SECURITY";
GRANT CREATE CREDENTIAL TO "SECURITY";
GRANT SET CONTAINER TO "SECURITY";
GRANT CREATE PLUGGABLE DATABASE TO "SECURITY";
GRANT FLASHBACK ARCHIVE ADMINISTER TO "SECURITY";
GRANT EM EXPRESS CONNECT TO "SECURITY";
GRANT DROP ANY SQL TRANSLATION PROFILE TO "SECURITY";
GRANT USE ANY SQL TRANSLATION PROFILE TO "SECURITY";
GRANT ALTER ANY SQL TRANSLATION PROFILE TO "SECURITY";
GRANT CREATE ANY SQL TRANSLATION PROFILE TO "SECURITY";
GRANT CREATE SQL TRANSLATION PROFILE TO "SECURITY";
GRANT ADMINISTER SQL MANAGEMENT OBJECT TO "SECURITY";
GRANT UPDATE ANY CUBE DIMENSION TO "SECURITY";
GRANT UPDATE ANY CUBE BUILD PROCESS TO "SECURITY";
GRANT DROP ANY CUBE BUILD PROCESS TO "SECURITY";
GRANT CREATE ANY CUBE BUILD PROCESS TO "SECURITY";
GRANT CREATE CUBE BUILD PROCESS TO "SECURITY";
GRANT INSERT ANY MEASURE FOLDER TO "SECURITY";
GRANT DROP ANY MEASURE FOLDER TO "SECURITY";
GRANT DELETE ANY MEASURE FOLDER TO "SECURITY";
GRANT CREATE ANY MEASURE FOLDER TO "SECURITY";
GRANT CREATE MEASURE FOLDER TO "SECURITY";
GRANT UPDATE ANY CUBE TO "SECURITY";
GRANT SELECT ANY CUBE TO "SECURITY";
GRANT DROP ANY CUBE TO "SECURITY";
GRANT CREATE ANY CUBE TO "SECURITY";
GRANT ALTER ANY CUBE TO "SECURITY";
GRANT CREATE CUBE TO "SECURITY";
GRANT SELECT ANY CUBE DIMENSION TO "SECURITY";
GRANT INSERT ANY CUBE DIMENSION TO "SECURITY";
GRANT DROP ANY CUBE DIMENSION TO "SECURITY";
GRANT DELETE ANY CUBE DIMENSION TO "SECURITY";
GRANT CREATE ANY CUBE DIMENSION TO "SECURITY";
GRANT ALTER ANY CUBE DIMENSION TO "SECURITY";
GRANT CREATE CUBE DIMENSION TO "SECURITY";
GRANT COMMENT ANY MINING MODEL TO "SECURITY";
GRANT ALTER ANY MINING MODEL TO "SECURITY";
GRANT SELECT ANY MINING MODEL TO "SECURITY";
GRANT DROP ANY MINING MODEL TO "SECURITY";
GRANT CREATE ANY MINING MODEL TO "SECURITY";
GRANT CREATE MINING MODEL TO "SECURITY";
GRANT EXECUTE ASSEMBLY TO "SECURITY";
GRANT EXECUTE ANY ASSEMBLY TO "SECURITY";
GRANT DROP ANY ASSEMBLY TO "SECURITY";
GRANT ALTER ANY ASSEMBLY TO "SECURITY";
GRANT CREATE ANY ASSEMBLY TO "SECURITY";
GRANT CREATE ASSEMBLY TO "SECURITY";
GRANT ALTER ANY EDITION TO "SECURITY";
GRANT DROP ANY EDITION TO "SECURITY";
GRANT CREATE ANY EDITION TO "SECURITY";
GRANT CREATE EXTERNAL JOB TO "SECURITY";
GRANT CHANGE NOTIFICATION TO "SECURITY";
GRANT CREATE ANY SQL PROFILE TO "SECURITY";
GRANT ADMINISTER ANY SQL TUNING SET TO "SECURITY";
GRANT ADMINISTER SQL TUNING SET TO "SECURITY";
GRANT ALTER ANY SQL PROFILE TO "SECURITY";
GRANT DROP ANY SQL PROFILE TO "SECURITY";
GRANT SELECT ANY TRANSACTION TO "SECURITY";
GRANT MANAGE SCHEDULER TO "SECURITY";
GRANT EXECUTE ANY CLASS TO "SECURITY";
GRANT EXECUTE ANY PROGRAM TO "SECURITY";
GRANT CREATE ANY JOB TO "SECURITY";
GRANT CREATE JOB TO "SECURITY";
GRANT ADVISOR TO "SECURITY";
GRANT IMPORT FULL DATABASE TO "SECURITY";
GRANT EXPORT FULL DATABASE TO "SECURITY";
GRANT GRANT ANY OBJECT PRIVILEGE TO "SECURITY";
GRANT FLASHBACK ANY TABLE TO "SECURITY";
GRANT DEBUG ANY PROCEDURE TO "SECURITY";
GRANT DEBUG CONNECT SESSION TO "SECURITY";
GRANT RESUMABLE TO "SECURITY";
GRANT ON COMMIT REFRESH TO "SECURITY";
GRANT MERGE ANY VIEW TO "SECURITY";
GRANT ADMINISTER DATABASE TRIGGER TO "SECURITY";
GRANT DROP ANY OUTLINE TO "SECURITY";
GRANT ALTER ANY OUTLINE TO "SECURITY";
GRANT CREATE ANY OUTLINE TO "SECURITY";
GRANT DROP ANY CONTEXT TO "SECURITY";
GRANT CREATE ANY CONTEXT TO "SECURITY";
GRANT DROP ANY DIMENSION TO "SECURITY";
GRANT ALTER ANY DIMENSION TO "SECURITY";
GRANT CREATE ANY DIMENSION TO "SECURITY";
GRANT CREATE DIMENSION TO "SECURITY";
GRANT UNDER ANY TABLE TO "SECURITY";
GRANT EXECUTE ANY INDEXTYPE TO "SECURITY";
GRANT GLOBAL QUERY REWRITE TO "SECURITY";
GRANT QUERY REWRITE TO "SECURITY";
GRANT UNDER ANY VIEW TO "SECURITY";
GRANT DROP ANY INDEXTYPE TO "SECURITY";
GRANT ALTER ANY INDEXTYPE TO "SECURITY";
GRANT CREATE ANY INDEXTYPE TO "SECURITY";
GRANT CREATE INDEXTYPE TO "SECURITY";
GRANT EXECUTE ANY OPERATOR TO "SECURITY";
GRANT DROP ANY OPERATOR TO "SECURITY";
GRANT ALTER ANY OPERATOR TO "SECURITY";
GRANT CREATE ANY OPERATOR TO "SECURITY";
GRANT CREATE OPERATOR TO "SECURITY";
GRANT EXECUTE ANY LIBRARY TO "SECURITY";
GRANT DROP ANY LIBRARY TO "SECURITY";
GRANT ALTER ANY LIBRARY TO "SECURITY";
GRANT CREATE ANY LIBRARY TO "SECURITY";
GRANT CREATE LIBRARY TO "SECURITY";
GRANT UNDER ANY TYPE TO "SECURITY";
GRANT EXECUTE ANY TYPE TO "SECURITY";
GRANT DROP ANY TYPE TO "SECURITY";
GRANT ALTER ANY TYPE TO "SECURITY";
GRANT CREATE ANY TYPE TO "SECURITY";
GRANT CREATE TYPE TO "SECURITY";
GRANT DROP ANY DIRECTORY TO "SECURITY";
GRANT CREATE ANY DIRECTORY TO "SECURITY";
GRANT DROP ANY MATERIALIZED VIEW TO "SECURITY";
GRANT ALTER ANY MATERIALIZED VIEW TO "SECURITY";
GRANT CREATE ANY MATERIALIZED VIEW TO "SECURITY";
GRANT CREATE MATERIALIZED VIEW TO "SECURITY";
GRANT GRANT ANY PRIVILEGE TO "SECURITY";
GRANT ANALYZE ANY TO "SECURITY";
GRANT ALTER RESOURCE COST TO "SECURITY";
GRANT DROP PROFILE TO "SECURITY";
GRANT ALTER PROFILE TO "SECURITY";
GRANT CREATE PROFILE TO "SECURITY";
GRANT DROP ANY TRIGGER TO "SECURITY";
GRANT ALTER ANY TRIGGER TO "SECURITY";
GRANT CREATE ANY TRIGGER TO "SECURITY";
GRANT CREATE TRIGGER TO "SECURITY";
GRANT EXECUTE ANY PROCEDURE TO "SECURITY";
GRANT DROP ANY PROCEDURE TO "SECURITY";
GRANT ALTER ANY PROCEDURE TO "SECURITY";
GRANT CREATE ANY PROCEDURE TO "SECURITY";
GRANT CREATE PROCEDURE TO "SECURITY";
GRANT FORCE ANY TRANSACTION TO "SECURITY";
GRANT FORCE TRANSACTION TO "SECURITY";
GRANT ALTER DATABASE TO "SECURITY";
GRANT AUDIT ANY TO "SECURITY";
GRANT ALTER ANY ROLE TO "SECURITY";
GRANT GRANT ANY ROLE TO "SECURITY";
GRANT DROP ANY ROLE TO "SECURITY";
GRANT CREATE ROLE TO "SECURITY";
GRANT DROP PUBLIC DATABASE LINK TO "SECURITY";
GRANT CREATE PUBLIC DATABASE LINK TO "SECURITY";
GRANT CREATE DATABASE LINK TO "SECURITY";
GRANT SELECT ANY SEQUENCE TO "SECURITY";
GRANT DROP ANY SEQUENCE TO "SECURITY";
GRANT ALTER ANY SEQUENCE TO "SECURITY";
GRANT CREATE ANY SEQUENCE TO "SECURITY";
GRANT CREATE SEQUENCE TO "SECURITY";
GRANT DROP ANY VIEW TO "SECURITY";
GRANT CREATE ANY VIEW TO "SECURITY";
GRANT CREATE VIEW TO "SECURITY";
GRANT DROP PUBLIC SYNONYM TO "SECURITY";
GRANT CREATE PUBLIC SYNONYM TO "SECURITY";
GRANT DROP ANY SYNONYM TO "SECURITY";
GRANT CREATE ANY SYNONYM TO "SECURITY";
GRANT CREATE SYNONYM TO "SECURITY";
GRANT DROP ANY INDEX TO "SECURITY";
GRANT ALTER ANY INDEX TO "SECURITY";
GRANT CREATE ANY INDEX TO "SECURITY";
GRANT DROP ANY CLUSTER TO "SECURITY";
GRANT ALTER ANY CLUSTER TO "SECURITY";
GRANT CREATE ANY CLUSTER TO "SECURITY";
GRANT CREATE CLUSTER TO "SECURITY";
GRANT REDEFINE ANY TABLE TO "SECURITY";
GRANT DELETE ANY TABLE TO "SECURITY";
GRANT UPDATE ANY TABLE TO "SECURITY";
GRANT INSERT ANY TABLE TO "SECURITY";
GRANT SELECT ANY TABLE TO "SECURITY";
GRANT COMMENT ANY TABLE TO "SECURITY";
GRANT LOCK ANY TABLE TO "SECURITY";
GRANT DROP ANY TABLE TO "SECURITY";
GRANT BACKUP ANY TABLE TO "SECURITY";
GRANT ALTER ANY TABLE TO "SECURITY";
GRANT CREATE ANY TABLE TO "SECURITY";
GRANT CREATE TABLE TO "SECURITY";
GRANT DROP ROLLBACK SEGMENT TO "SECURITY";
GRANT ALTER ROLLBACK SEGMENT TO "SECURITY";
GRANT CREATE ROLLBACK SEGMENT TO "SECURITY";
GRANT DROP USER TO "SECURITY";
GRANT ALTER USER TO "SECURITY";
GRANT BECOME USER TO "SECURITY";
GRANT CREATE USER TO "SECURITY";
GRANT UNLIMITED TABLESPACE TO "SECURITY";
GRANT DROP TABLESPACE TO "SECURITY";
GRANT MANAGE TABLESPACE TO "SECURITY";
GRANT ALTER TABLESPACE TO "SECURITY";
GRANT CREATE TABLESPACE TO "SECURITY";
GRANT RESTRICTED SESSION TO "SECURITY";
GRANT ALTER SESSION TO "SECURITY";
GRANT CREATE SESSION TO "SECURITY";
GRANT AUDIT SYSTEM TO "SECURITY";
GRANT ALTER SYSTEM TO "SECURITY";
-- new object type path: SCHEMA_EXPORT/DEFAULT_ROLE
 ALTER USER "SECURITY" DEFAULT ROLE ALL;
-- new object type path: SCHEMA_EXPORT/TABLESPACE_QUOTA
DECLARE 
  TEMP_COUNT NUMBER; 
  SQLSTR VARCHAR2(200); 
BEGIN 
  SQLSTR := 'ALTER USER "SECURITY" QUOTA UNLIMITED ON "DATA01"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION 
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN 
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES 
              WHERE TABLESPACE_NAME = ''DATA01'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN; 
      ELSE RAISE; 
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/
-- new object type path: SCHEMA_EXPORT/PRE_SCHEMA/PROCACT_SCHEMA
-- CONNECT SECURITY

BEGIN 
sys.dbms_logrep_imp.instantiate_schema(schema_name=>SYS_CONTEXT('USERENV','CURRENT_SCHEMA'), export_db_name=>'SFT.CONEXIA.COM', inst_scn=>'3887179');
COMMIT; 
END; 
/ 
-- new object type path: SCHEMA_EXPORT/TABLE/TABLE
-- CONNECT SYS
CREATE TABLE "SECURITY"."ACCESS_POINT" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"CODE" VARCHAR2(5 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"DATE_INSERT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"DATE_UPDATE" TIMESTAMP (6) DEFAULT NULL, 
	"DATE_DELETE" TIMESTAMP (6) DEFAULT NULL, 
	"DELETED" VARCHAR2(1 BYTE) DEFAULT 'F' NOT NULL ENABLE, 
	"VERSION" NUMBER(6,0) DEFAULT 1 NOT NULL ENABLE, 
	"USER_REQUEST_ID" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
CREATE TABLE "SECURITY"."API_KEY_ACCESS_POINT" 
   (	"ID" NUMBER(10,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 4 CACHE 20 NOORDER  NOCYCLE  NOT NULL ENABLE, 
	"API_KEY" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	"ACCESS_POINT_ID" NUMBER(22,0), 
	"VALID_FROM" DATE, 
	"VALID_TO" DATE, 
	"DATE_INSERT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"DATE_UPDATE" TIMESTAMP (6) DEFAULT NULL, 
	"DATE_DELETE" TIMESTAMP (6) DEFAULT NULL, 
	"DELETED" VARCHAR2(1 BYTE) DEFAULT 'F' NOT NULL ENABLE, 
	"VERSION" NUMBER(6,0) DEFAULT 1 NOT NULL ENABLE, 
	"USER_REQUEST_ID" VARCHAR2(240 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA01" ;
-- new object type path: SCHEMA_EXPORT/TABLE/GRANT/OWNER_GRANT/OBJECT_GRANT
-- CONNECT SECURITY
GRANT DELETE ON "SECURITY"."ACCESS_POINT" TO "APPROLE";
GRANT UPDATE ON "SECURITY"."ACCESS_POINT" TO "APPROLE";
GRANT SELECT ON "SECURITY"."ACCESS_POINT" TO "APPROLE";
GRANT INSERT ON "SECURITY"."ACCESS_POINT" TO "APPROLE";
GRANT UPDATE ON "SECURITY"."API_KEY_ACCESS_POINT" TO "APPROLE";
GRANT SELECT ON "SECURITY"."API_KEY_ACCESS_POINT" TO "APPROLE";
GRANT INSERT ON "SECURITY"."API_KEY_ACCESS_POINT" TO "APPROLE";
GRANT DELETE ON "SECURITY"."API_KEY_ACCESS_POINT" TO "APPROLE";
-- new object type path: SCHEMA_EXPORT/TABLE/AUDIT_OBJ
-- CONNECT SYS
 AUDIT DELETE, INSERT, UPDATE ON "SECURITY"."ACCESS_POINT" BY ACCESS WHENEVER SUCCESSFUL;
  
 AUDIT DELETE, INSERT, UPDATE ON "SECURITY"."ACCESS_POINT" BY ACCESS WHENEVER NOT SUCCESSFUL;
  
 AUDIT DELETE, INSERT, UPDATE ON "SECURITY"."API_KEY_ACCESS_POINT" BY ACCESS WHENEVER SUCCESSFUL;
  
 AUDIT DELETE, INSERT, UPDATE ON "SECURITY"."API_KEY_ACCESS_POINT" BY ACCESS WHENEVER NOT SUCCESSFUL;
  
-- new object type path: SCHEMA_EXPORT/TABLE/IDENTITY_COLUMN
ALTER TABLE "SECURITY"."ACCESS_POINT" MODIFY ("ID" GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH  LIMIT VALUE  CACHE 20 NOORDER  NOCYCLE );
ALTER TABLE "SECURITY"."API_KEY_ACCESS_POINT" MODIFY ("ID" GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH  LIMIT VALUE  CACHE 20 NOORDER  NOCYCLE );
-- new object type path: SCHEMA_EXPORT/FUNCTION/FUNCTION
-- CONNECT SECURITY
CREATE EDITIONABLE FUNCTION            AUTHENTICATE_ACCESS_BY_API_D (apikey VARCHAR2, accesspoint VARCHAR2)
RETURN NUMBER
IS
valid NUMBER;
BEGIN
SELECT CASE count(1) WHEN 0 THEN 0 ELSE 1 END
   into valid
	FROM "SECURITY".API_KEY_ACCESS_POINT apk
	JOIN "SECURITY".ACCESS_POINT ap on apk.access_point_id = ap.ID
WHERE apk.API_KEY = apikey
AND ap.CODE = accesspoint
AND current_date BETWEEN apk.VALID_FROM AND apk.VALID_TO;
return (valid);
END;
/
CREATE EDITIONABLE FUNCTION            AUTHENTICATE_ACCESS_BY_API_KEY (apikey VARCHAR2, accesspoint VARCHAR2)
RETURN NUMBER
IS
valid NUMBER;
BEGIN
SELECT CASE count(1) WHEN 0 THEN 0 ELSE 1 END
   into valid
	FROM "SECURITY".API_KEY_ACCESS_POINT apk
	JOIN "SECURITY".ACCESS_POINT ap on apk.access_point_id = ap.ID
WHERE apk.API_KEY = apikey
AND ap.CODE = accesspoint
AND current_date BETWEEN apk.VALID_FROM AND apk.VALID_TO;
return (valid);
END;
/
-- new object type path: SCHEMA_EXPORT/FUNCTION/GRANT/OWNER_GRANT/OBJECT_GRANT
GRANT EXECUTE ON "SECURITY"."AUTHENTICATE_ACCESS_BY_API_KEY" TO "APPROLE";
-- new object type path: SCHEMA_EXPORT/FUNCTION/ALTER_FUNCTION

ALTER FUNCTION "SECURITY"."AUTHENTICATE_ACCESS_BY_API_D" 
  COMPILE 
    PLSQL_OPTIMIZE_LEVEL=  2
    PLSQL_CODE_TYPE=  INTERPRETED
    PLSQL_DEBUG=  FALSE    PLSCOPE_SETTINGS=  'IDENTIFIERS:NONE'

 REUSE SETTINGS TIMESTAMP '2018-09-12 15:12:57'
/

ALTER FUNCTION "SECURITY"."AUTHENTICATE_ACCESS_BY_API_KEY" 
  COMPILE 
    PLSQL_OPTIMIZE_LEVEL=  2
    PLSQL_CODE_TYPE=  INTERPRETED
    PLSQL_DEBUG=  FALSE    PLSCOPE_SETTINGS=  'IDENTIFIERS:NONE'

 REUSE SETTINGS TIMESTAMP '2018-09-12 15:13:28'
/
-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/INDEX
CREATE INDEX "SECURITY"."SEC_AP_CODE_IDX" ON "SECURITY"."ACCESS_POINT" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01" PARALLEL 1 ;

  ALTER INDEX "SECURITY"."SEC_AP_CODE_IDX" NOPARALLEL;
BEGIN 
NULL;
END;
/

BEGIN 
NULL;
END;
/

-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/CONSTRAINT
-- CONNECT SYS
ALTER TABLE "SECURITY"."ACCESS_POINT" ADD CONSTRAINT "ACCESS_POINT_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "SECURITY"."ACCESS_POINT_PK" ON "SECURITY"."ACCESS_POINT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01" )  ENABLE;
ALTER TABLE "SECURITY"."API_KEY_ACCESS_POINT" ADD CONSTRAINT "API_KEY_ACCESS_POINT_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "SECURITY"."API_KEY_ACCESS_POINT_PK" ON "SECURITY"."API_KEY_ACCESS_POINT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "INDEX01" )  ENABLE;
-- new object type path: SCHEMA_EXPORT/TABLE/INDEX/STATISTICS/INDEX_STATISTICS
-- new object type path: SCHEMA_EXPORT/TABLE/CONSTRAINT/REF_CONSTRAINT
ALTER TABLE "SECURITY"."API_KEY_ACCESS_POINT" ADD CONSTRAINT "API_KEY_ACC_POINT_ACC_POINT_FK" FOREIGN KEY ("ACCESS_POINT_ID")
	  REFERENCES "SECURITY"."ACCESS_POINT" ("ID") ENABLE;
-- new object type path: SCHEMA_EXPORT/TABLE/STATISTICS/TABLE_STATISTICS
-- new object type path: SCHEMA_EXPORT/STATISTICS/MARKER
